### ISSUE TITLE
Set search to match title first

### ISSUE THREAD

**Issue by tripathiakshit** [appetizermonster/hain#155]
This screen shot is a pretty good example of what I mean

![x](https://cloud.githubusercontent.com/assets/4148576/15992483/69997c72-309b-11e6-8f53-38633f9a7b7e.png)

Is there any way to make sure it matches with titles first?

**Comment by appetizermonster** [comment]
I agree and suppose `Atom` should be on the top of the results.
I will try to fix it

**Comment by Fannon** [comment]
Is there a way to disable the "recent items" feature at all? It looks like it is causing this issue, as recent items are always prefereed. Maybe an item that has been executed previously could be "tagged" as favorite (and gain a slight score upgrade), but does not appear in its own section.

Using Hain since a few weeks, great work you're doing!

**Comment by appetizermonster** [comment]
@Fannon I believe we don't need to another option to disable it, but I suppose your suggestion is more useful. I will try. and Thanks for the compliment!

**Comment by appetizermonster** [comment]
Resolved at 80da941b5ae835afbab5c4fccefb3cd9ddd7ca30

**Comment by cpriest** [comment]
Please verify this is still an issue with v0.6, I believe this has been addressed.  If not, please re-open.
